### PR TITLE
Added a nft-preview-card-component project

### PR DESCRIPTION
**Pull request by Nick-h4ck3r**

### CODE REVIEW

**Comment by Ayushsingh07** [comment]
its a work from Nakoya Wilson. 
do something on your own .even a simple program can be accepted like prime number program .
P.S-star the repo and do follow.

**Comment by Nick-h4ck3r** [comment]
Actually, the code is mine totally. I have submitted as a challange on Frontend Mentor Website. You get a demo images there and develop a similar looking frontend using html and css. I do have coded it locally and submitted. Not to mention.

Have a nice day!

**Comment by Ayushsingh07** [comment]
ok got it.
nice work then. keep it up

**Comment by Nick-h4ck3r** [comment]
Thanks man! 👍

**Pull request merged**
